### ISSUE TITLE
BigInt can handle at max 2^53 integer

### ISSUE THREAD

**Issue by chientrm** [theinternetfolks/snowflake#1]
How does this library generating 63 bit id with BigInt?

**Comment by spitliner** [comment]
@chientrm  BigInt can handle arbitrary size as long as your PC memory support it: https://v8.dev/blog/bigint#tl%3Bdr

**Comment by monkfromearth** [comment]
Hi OP.

You can verify the same here: https://www.rapidtables.com/convert/number/decimal-to-binary.html

You can use a sample Snowflake generated from the library or here: `6917062538869867520` from the README.

Thanks [spitliner](https://github.com/spitliner) for the help as well.

![image](https://github.com/theinternetfolks/snowflake/assets/19186342/d994c86a-4808-4007-a37a-bf016a5d69a8)
